[package]
name = "fem_gui"
version = "0.1.0"
edition = "2021" 

[dependencies]
fem_comp = { path = "../fem_comp" }
raylib = { version = "5.0" } 
nfd = { git = "https://github.com/MFEK/nfd.rlib.git" }
