[package]
name = "fem_gui"
version = "0.1.0"
edition = "2021" 

[dependencies]
bevy = { version = "0.13.0", features = ["dynamic_linking"] }
fem_comp = { path = "../fem_comp" }

[profile.dev]
opt-level = 1
