[package]
name = "fem_gui"
version = "0.1.0"
edition = "2021" 

[dependencies]
fem_comp = { path = "../fem_comp" }
raylib =  {git = "https://github.com/raylib-rs/raylib-rs.git" }
nfd = { git = "https://github.com/MFEK/nfd.rlib.git" }
